# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

#project name
PROJECT:
  name: "WP Voting"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "assets"
  php:
    - "**/*.php"
    - "!node_modules/**"
    - "!.git/**"

  img: "src/img/*.{png,jpg,gif}"
  js: "src/*.js"
  css: "src/*.css"

  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/js/*.js"
